version: '3.9'

services:

  naming-server:
    image: arbaaz06/msc-naming-server:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8761:8761"
    networks:
      - msc-microservice-network


      
  users-service:
    image: arbaaz06/msc-users-service:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - msc-microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

      
  wallet-service:
    image: arbaaz06/msc-wallet-service:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8100:8100"
    networks:
      - msc-microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

      
  menu-service:
    image: arbaaz06/msc-menu-service:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8200:8200"
    networks:
      - msc-microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

      
  order-service:
    image: arbaaz06/msc-order-service:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8300:8300"
    networks:
      - msc-microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

      
  basket-service:
    image: arbaaz06/msc-basket-service:0.0.4-SNAPSHOT
    ports:
      - "0.0.0.0:8400:8400"
    networks:
      - msc-microservice-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka


      
networks:
  msc-microservice-network: